# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'PLCAudioRecorderDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

pod 'FreeStreamer'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'JHChainableAnimations'
pod 'BlocksKit'
end
